-- FF4J core tables (required)
CREATE TABLE IF NOT EXISTS FF4J_FEATURES (
    FEAT_UID VARCHAR(100) PRIMARY KEY,
    ENABLE INTEGER NOT NULL,
    DESCRIPTION VARCHAR(1000),
    STRATEGY VARCHAR(1000),
    EXPRESSION VARCHAR(255),
    GROUPNAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS FF4J_ROLES (
    FEAT_UID VARCHAR(100) REFERENCES FF4J_FEATURES(FEAT_UID),
    ROLE_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (FEAT_UID, ROLE_NAME)
);

-- User roles table (custom)
CREATE TABLE IF NOT EXISTS FF4J_USER_ROLES (
    USERNAME VARCHAR(100) NOT NULL,
    ROLE_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (USERNAME, ROLE_NAME)
);

-- Insert sample data
INSERT INTO FF4J_USER_ROLES (USERNAME, ROLE_NAME) VALUES 
('admin', 'ADMIN'),
('admin', 'READONLY'),
('user1', 'READONLY'),
('user1', 'USER');
